# Generated by Django 2.2.14 on 2020-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('post_title', models.TextField()),
                ('post_desc', models.CharField(max_length=100)),
                ('post_author', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
