# Generated by Django 2.2.14 on 2020-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20200820_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.TextField(),
        ),
    ]
